### ISSUE TITLE
Users can't enabale the Touneament if teams app.

### ISSUE THREAD

**Issue by RoryCG97** [OfficeDev/microsoft-teams-apps-tournament-of-teams#14]
Hello,
We have had a occurring issue where users cant enable the tournament of teams.
Users would be waiting more then 10 minuets and it still doesn't enable.
They would then do a refresh but it would still persist.
Is there a way to fix this as it would be very helpful.

Best Regards,
<img width="472" alt="TOT issue" src="https://user-images.githubusercontent.com/126159287/220891614-07a3f760-8957-4391-9f0a-fe21b8a6b4fc.PNG">

Rory

**Comment by v-saikirang** [comment]
Hi @RoryCG97,

Thanks for reaching out to us.

1) Can you please open the app in browser an share the console logs.
2) Check if the site collection "TournamentOfTeams" is created. Please check both "Active Sites" and "Deleted Sites" in Sharepoint Admin Center.
![image](https://user-images.githubusercontent.com/87538202/220897308-d1026b25-1e62-412a-b3c2-811ae323011f.png)

3) If the site collection is created please share a screenshot of the Site Contents page.

Thanks.

**Comment by RoryCG97** [comment]
Hello, 
How do you do point one.

And below is a screen shot of the site collection.
![image](https://user-images.githubusercontent.com/126159287/222106113-a255a77f-2bf1-4b6c-a916-1e8f209fed6c.png)

Best Regards,
Rory

**Comment by v-saikirang** [comment]
Hi @RoryCG97,

Thanks for the screenshot.

Please open teams in chrome browser, open the TOT app, open developer tools, recreate the error and save the console logs. Please refer to this link  for generating console logs: https://confluence.snapbytes.com/time-to-sla/knowledge-base/guide/how-to-save-chrome-console-logs-to-a-file
Thanks.

**Comment by RoryCG97** [comment]
Sorry for the late response.
Here are the logs.

Best Regards,
Rory
[teams.microsoft.com-1678275506243.log](https://github.com/OfficeDev/microsoft-teams-apps-tournament-of-teams/files/10920207/teams.microsoft.com-1678275506243.log)

**Comment by v-saikirang** [comment]
Hi @RoryCG97 ,

Thanks for the logs. Request you to share couple inputs:

1) When you navigate to the app do you see the "Enable Tournament of Teams" tile. Can you please share a screenshot.
2) May I know if you have added "Everyone" to the Sharepoint Members group under permissions as specified in the [wiki ](https://github.com/OfficeDev/microsoft-teams-apps-tournament-of-teams/wiki/Deployment-Guide#first-run-experience-add-tournament-of-teams-tab-in-teams)section "8. Grant Permissions to users". If not, please try adding the users and refreshing the app.
Thanks.
