### ISSUE TITLE
Tournament actions not saving once marked complete

### ISSUE THREAD

**Issue by jenpeabody** [OfficeDev/microsoft-teams-apps-tournament-of-teams#15]
I have a live tournament going on now and today the issue popped up where when users mark an action complete and click the save button, nothing happens. It stays under Pending Actions. Could use some help here as this is the first time we have launched this app company-wide.

**Comment by v-saikirang** [comment]
Hi @jenpeabody,

Thanks for reaching out to us. Can you please share a screenshot of the My Dashboard screen. And also please open teams in browser, click on Save and share the console logs so we can continue to troubleshoot.

Thanks.

**Comment by jenpeabody** [comment]
Do you think it because I have multiple tasks with the same name even though they are assigned a different category?
![ToT](https://user-images.githubusercontent.com/104847055/233442243-c59bbac7-db4d-4f34-a3b1-6f890894abcf.png)

**Comment by jenpeabody** [comment]
Can I edit them without having to end the tournament and restart? Although, looking at my leaderboard, there are a couple of people who I believe completed all the tasks, so not sure. Could you advise on how I can access console logs?

**Comment by v-saikirang** [comment]
Hi @jenpeabody,

Yes that seems to be the issue. The Tournament "Action" is expected to be unique value which is causing the conflict here. You can try changing the Action in the "Tournament Actions" list for that particular tournament. But this may cause discrepancies if other users have already completed the previous action which may show different tournaments results. You can fix them manually from "User Actions" list if needed. You should still be modifying the duplicate actions in "Actions" list to avoid issues with new tournaments going forward. If possible the best option would be to create a new tournament after fixing the "Actions" list. Please let me know if you need more information. We will check the feasibility to handle this scenario if possible in our future release.
Thanks.

**Comment by jenpeabody** [comment]
Hello!
Thank you for your suggestions! They have worked! I appreciate your help!
