### ISSUE TITLE
Any plans for an upgrade to reduce vulnerabilities?

### ISSUE THREAD

**Issue by ekdegerman** [OfficeDev/microsoft-teams-apps-tournament-of-teams#9]
We are looking to use this app to engage our champions network and noticed when running it through our dependency and source scanning that it comes back with some additional vulnerabilities compared to the components we are already using. I can see that it was based on SharePoint Framework 1.13.0, which is getting pretty old. Do you have any plans to upgrade the SPFx version along with other dependencies or is this just a one time release and any future updates will be up to the community? Will this and the champions management app continue to exist in parallel or is this app meant to replace all or part of champions management?

**Comment by v-saikirang** [comment]
Hi @ekdegerman,

Thanks for your interest in the app. SPFX 1.13.0 was the most stable version when we released this app last time. But we will definitely plan to upgrade it to a latest and stable version in our future releases. We do not have any specific time line for our next release yet. 
As of now the Tournaments of Teams will exist in both champions management platform and as well as stand alone version. But we might consider any new enhancements to the Tournament of teams only to the stand alone app. So if you are interested in Tournament of Teams module we suggest install the stand alone version so you will not miss out any future updates to this area.

Please let me know if you need more information.
Thanks.

**Comment by ekdegerman** [comment]
Thanks for the quick response! Hoping for an upgrade soon... :) 

Just one more question regarding dependencies. I see some that are classified as dependencies in this web part but tend to belong in the devDependencies category (e.g. webpack, typescript, ..). Could this possibly be reviewed as well to facilitate vulnerability scanning of dependencies used runtime in a better way?

**Comment by v-saikirang** [comment]
Hi @ekdegerman,

Sure. We will review and try to address the dependencies in our future releases.

Thanks for your feedback.
Please let me know if you need more information.

Thanks.
